### ISSUE TITLE
Is it possible to make pdict reversible?

### ISSUE THREAD

**Issue by rindis** [noahbenson/pcollections#4]
It appears that `pdict` preserves insertion order (which I hope is by design and will continue to be the case going forward), but it does not support `reversed`. Would this be possible to implement?

**Comment by noahbenson** [comment]
Yes, good point! My intention is to implement everything to be as similar as possible to `dict`, so I will likely implement `reversed` to be equivalent to `dict`'s `__reversed__` method (where it just returns a reversed iterator for the keys). Creating a reversed dictionary is possible but it isn't efficient—the underlying `phamt` library doesn't support reversal so creating a reversed dictionary would be `O(n log n)`. But with the reversed keys, it should be possible to do something like `pdict((k,d[k]) for k in reversed(d))`.

The insertion order is preserved by design and will remain!

**Comment by noahbenson** [comment]
Commit 4cacc5d adds reversed to `pdict` and `tdict` (and the child types `ldict` and `tldict`).

**Comment by noahbenson** [comment]
(Uploaded as version 0.2.5 on PyPI.)
